# FROM quay.io/jupyter/datascience-notebook:python-3.11.6
FROM docker.io/ucsb/pstat134:v20260102 

USER root

RUN groupadd jovyan \
    && usermod -g jovyan -a -G users,sudo jovyan \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        zsh npm libcairo2-dev libtiff-dev && \
    apt-get clean && \
    npm install -g playwright && \
    playwright install --with-deps && \
    playwright install chromium

USER ${NB_USER}

### R compiler and CRAN mirror settings
RUN R -e "dotR <- file.path(Sys.getenv('HOME'), '.R'); if(!file.exists(dotR)){ dir.create(dotR) }; Makevars <- file.path(dotR, 'Makevars'); if (!file.exists(Makevars)){  file.create(Makevars) }; cat('\nCXXFLAGS=-O3 -fPIC -Wno-unused-variable -Wno-unused-function', 'CXX14 = g++ -std=c++1y -fPIC', 'CXX = g++', 'CXX11 = g++', file = Makevars, sep = '\n', append = TRUE)" && \
    chmod 666 ${HOME}/.R/Makevars && \
    R -e "dotRprofile <- file.path(Sys.getenv('HOME'), '.Rprofile'); if(!file.exists(dotRprofile)){ file.create(dotRprofile) }; cat('local({r <- getOption(\"repos\")', 'r[\"CRAN\"] <- \"https://cloud.r-project.org\"', 'options(repos=r)', '})', file = dotRprofile, sep = '\n', append = TRUE)" && \
    chmod 666 ${HOME}/.Rprofile

RUN R -q -e 'remotes::install_version("reticulate")' && \
    R -q -e 'remotes::install_version("markdown", version="1.12")' && \
    R -q -e 'remotes::install_version("languageserver", version="0.3.16")' && \
    R -q -e 'remotes::install_version("httpgd", version="2.0.1")' && \
    R -q -e 'remotes::install_github("ManuelHentschel/vscDebugger")'

RUN R -q -e 'remotes::install_version("bootstrap", version="2019.6")' && \
    R -q -e 'remotes::install_version("fastICA", version="1.2-7")' && \
    R -q -e 'if (!require("BiocManager", quietly = TRUE)) {install.packages("BiocManager")}; BiocManager::install("Biobase")' && \
    R -q -e 'remotes::install_version("NMF")' && \
    R -q -e 'remotes::install_version("resample")' && \
    conda init zsh
